### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by 0xspade** [allfro/BurpKit#13]
Hello Team,

Im having an issue on the New release and in the v.1.02 release.. it comes up with error which i dont know what is it :D 

Here's the Screenshot
PS: Im just using Burp Suite Cracked
![screenshot at 2017-06-05 14-06-47](https://cloud.githubusercontent.com/assets/18681023/26772529/a80d0768-49f8-11e7-8fbb-466e553aca27.png)

**Comment by allfro** [comment]
Can't help without the full stacktrace man

**Comment by 0xspade** [comment]
what kind of Full StackTrace?

**Comment by 0xspade** [comment]
Here's my Latest Screenshot
![screenshot at 2017-06-06 10-43-51](https://cloud.githubusercontent.com/assets/18681023/26811562/3cf3ed36-4aa5-11e7-96dd-e2a94953fe4d.png)

**Comment by Hax0rG1rl** [comment]
Same issue here trying to install it. BurpKit 1.03-pre / Java platform is 1.8.0_131 / Burp 1.7.24 Pro.

Burp is throwing back this:

```
java.lang.ClassNotFoundException: javafx.embed.swing.JFXPanel
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at burp.gng.a(Unknown Source)
	at burp.gng.<init>(Unknown Source)
	at burp.pwc.a(Unknown Source)
	at burp.pyb.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)
```

Any advice? 

Cheers

**Comment by posi91** [comment]
Hello how are you, could someone fix this error? Currently I present the same output error.
I have openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-1-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)
Burp Suite Pro 1.7.32 Licensed

**Comment by posi91** [comment]
Reading a bit I found this thread https://github.com/thirdy/durian/issues/38, where I made the installation of the openjfx package and with this I solved the error :)

apt-get install openjfx #Test in Kali linux 2018

sl2 from colombia

**Comment by Hax0rG1rl** [comment]
@posi91 I do suspect this project is dead. So, do not expect any miracles :)

**Comment by ksg97031** [comment]
Burp was crash after applying openjfx library :(
