### ISSUE TITLE
Black Screen and Errors

### ISSUE THREAD

**Issue by urbanadventurer** [allfro/BurpKit#5]
I have the blank screen problem too. I installed Java 1.8 in Kali 2.0 using the following script:
# installed java 1.8 with this

update-alternatives --install /usr/bin/java java /opt/jdk1.8.0_51/bin/java 1
update-alternatives --install /usr/bin/javac javac /opt/jdk1.8.0_51/bin/javac 1
update-alternatives --install /usr/lib/mozilla/plugins/libjavaplugin.so mozilla-javaplugin.so /opt/jdk1.8.0_51/jre/lib/amd64/libnpjp2.so 1
update-alternatives --set java /opt/jdk1.8.0_51/bin/java
update-alternatives --set javac /opt/jdk1.8.0_51/bin/javac
update-alternatives --set mozilla-javaplugin.so /opt/jdk1.8.0_51/jre/lib/amd64/libnpjp2.so
# java -version

java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)

When including BurpKit into Burp I get the following Stack Trace:

java.lang.ExceptionInInitializerError
    at com.redcanari.ui.WebKitBrowser.createScene(WebKitBrowser.java:154)
    at com.redcanari.ui.WebKitBrowser$$Lambda$81/620552856.run(Unknown Source)
    at com.sun.javafx.application.PlatformImpl.lambda$null$170(PlatformImpl.java:295)
    at com.sun.javafx.application.PlatformImpl$$Lambda$80/2028583889.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$171(PlatformImpl.java:294)
    at com.sun.javafx.application.PlatformImpl$$Lambda$79/96487321.run(Unknown Source)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
    at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
    at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139)
    at com.sun.glass.ui.gtk.GtkApplication$$Lambda$68/1414084945.run(Unknown Source)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
    at com.sun.javafx.css.StyleManager.getURL(StyleManager.java:840)
    at com.sun.javafx.css.StyleManager.loadStylesheetUnPrivileged(StyleManager.java:1029)
    at com.sun.javafx.css.StyleManager.loadStylesheet(StyleManager.java:890)
    at com.sun.javafx.css.StyleManager._setDefaultUserAgentStylesheet(StyleManager.java:1338)
    at com.sun.javafx.css.StyleManager.setUserAgentStylesheets(StyleManager.java:1179)
    at com.sun.javafx.application.PlatformImpl.lambda$_setPlatformUserAgentStylesheet$179(PlatformImpl.java:698)
    at com.sun.javafx.application.PlatformImpl$$Lambda$89/1729821598.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.application.PlatformImpl._setPlatformUserAgentStylesheet(PlatformImpl.java:697)
    at com.sun.javafx.application.PlatformImpl.setPlatformUserAgentStylesheet(PlatformImpl.java:548)
    at com.sun.javafx.application.PlatformImpl.setDefaultPlatformUserAgentStylesheet(PlatformImpl.java:512)
    at javafx.scene.control.Control.<clinit>(Control.java:87)
    ... 12 more
java.lang.NoClassDefFoundError: org.controlsfx.control.ControlsFXControl
    at com.redcanari.ui.JavaScriptEditor.<init>(JavaScriptEditor.java:52)
    at com.redcanari.ui.JavaScriptEditor.<init>(JavaScriptEditor.java:66)
    at com.redcanari.ui.JavaScriptEditorTab.init(JavaScriptEditorTab.java:35)
    at com.redcanari.ui.JavaScriptEditorTab$$Lambda$96/440177638.run(Unknown Source)
    at com.sun.javafx.application.PlatformImpl.lambda$null$170(PlatformImpl.java:295)
    at com.sun.javafx.application.PlatformImpl$$Lambda$80/2028583889.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$171(PlatformImpl.java:294)
    at com.sun.javafx.application.PlatformImpl$$Lambda$79/96487321.run(Unknown Source)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
    at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
    at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139)
    at com.sun.glass.ui.gtk.GtkApplication$$Lambda$68/1414084945.run(Unknown Source)
    at java.lang.Thread.run(Thread.java:745)
java.lang.NoClassDefFoundError: Could not initialize class org.controlsfx.control.MasterDetailPane
    at com.redcanari.ui.WebKitBrowser.createScene(WebKitBrowser.java:154)
    at com.redcanari.ui.WebKitBrowser$$Lambda$81/620552856.run(Unknown Source)
    at com.sun.javafx.application.PlatformImpl.lambda$null$170(PlatformImpl.java:295)
    at com.sun.javafx.application.PlatformImpl$$Lambda$80/2028583889.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$171(PlatformImpl.java:294)
    at com.sun.javafx.application.PlatformImpl$$Lambda$79/96487321.run(Unknown Source)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
    at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
    at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139)
    at com.sun.glass.ui.gtk.GtkApplication$$Lambda$68/1414084945.run(Unknown Source)
    at java.lang.Thread.run(Thread.java:745)
java.lang.NoClassDefFoundError: Could not initialize class org.controlsfx.control.MasterDetailPane
    at com.redcanari.ui.WebKitBrowser.createScene(WebKitBrowser.java:154)
    at com.redcanari.ui.WebKitBrowser$$Lambda$81/620552856.run(Unknown Source)
    at com.sun.javafx.application.PlatformImpl.lambda$null$170(PlatformImpl.java:295)
    at com.sun.javafx.application.PlatformImpl$$Lambda$80/2028583889.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$171(PlatformImpl.java:294)
    at com.sun.javafx.application.PlatformImpl$$Lambda$79/96487321.run(Unknown Source)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
    at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
    at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139)
    at com.sun.glass.ui.gtk.GtkApplication$$Lambda$68/1414084945.run(Unknown Source)
    at java.lang.Thread.run(Thread.java:745)
java.lang.NoClassDefFoundError: Could not initialize class org.controlsfx.control.MasterDetailPane
    at com.redcanari.ui.WebKitBrowser.createScene(WebKitBrowser.java:154)
    at com.redcanari.ui.WebKitBrowser$$Lambda$81/620552856.run(Unknown Source)
    at com.sun.javafx.application.PlatformImpl.lambda$null$170(PlatformImpl.java:295)
    at com.sun.javafx.application.PlatformImpl$$Lambda$80/2028583889.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$171(PlatformImpl.java:294)
    at com.sun.javafx.application.PlatformImpl$$Lambda$79/96487321.run(Unknown Source)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
    at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
    at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139)
    at com.sun.glass.ui.gtk.GtkApplication$$Lambda$68/1414084945.run(Unknown Source)
    at java.lang.Thread.run(Thread.java:745)
java.lang.NoClassDefFoundError: Could not initialize class org.controlsfx.control.MasterDetailPane
    at com.redcanari.ui.WebKitBrowser.createScene(WebKitBrowser.java:154)
    at com.redcanari.ui.WebKitBrowser$$Lambda$81/620552856.run(Unknown Source)
    at com.sun.javafx.application.PlatformImpl.lambda$null$170(PlatformImpl.java:295)
    at com.sun.javafx.application.PlatformImpl$$Lambda$80/2028583889.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$171(PlatformImpl.java:294)
    at com.sun.javafx.application.PlatformImpl$$Lambda$79/96487321.run(Unknown Source)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
    at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
    at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139)
    at com.sun.glass.ui.gtk.GtkApplication$$Lambda$68/1414084945.run(Unknown Source)
    at java.lang.Thread.run(Thread.java:745)
java.lang.NoClassDefFoundError: Could not initialize class org.controlsfx.control.MasterDetailPane
    at com.redcanari.ui.WebKitBrowser.createScene(WebKitBrowser.java:154)
    at com.redcanari.ui.WebKitBrowser$$Lambda$81/620552856.run(Unknown Source)
    at com.sun.javafx.application.PlatformImpl.lambda$null$170(PlatformImpl.java:295)
    at com.sun.javafx.application.PlatformImpl$$Lambda$80/2028583889.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$171(PlatformImpl.java:294)
    at com.sun.javafx.application.PlatformImpl$$Lambda$79/96487321.run(Unknown Source)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
    at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
    at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139)
    at com.sun.glass.ui.gtk.GtkApplication$$Lambda$68/1414084945.run(Unknown Source)
    at java.lang.Thread.run(Thread.java:745)

**Comment by allfro** [comment]
Thanks for reporting. I am currently investigating this issue with the
other users as well. My suggestion for now is to use a different OS as the
JVM in Linux appears to suffer from an unknown/unverified race condition. I
am currently investigating workarounds.

**Comment by allfro** [comment]
See latest release for fix: https://github.com/allfro/BurpKit/releases/tag/v1.01-pre
