### ISSUE TITLE
Getting ClassNotFoundException on com.sun.javafx.Utils

### ISSUE THREAD

**Issue by Shaika-Dzari** [allfro/BurpKit#8]
Hi,

I'm trying burpkit (after attending your talk at the hackfest) and I'm getting a class not found exception after enabling the proxying.

Config : 
Archlinux, jdk 1.8.60

Stack : 

```
Warning: context class loader for JFX thread returned null.
Nov 06, 2015 10:53:33 PM com.sun.webkit.network.URLLoader doRun
WARNING: Unexpected error
java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 302 Found"
        at sun.net.www.protocol.http.HttpURLConnection.doTunneling(HttpURLConnection.java:2085)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
        at com.redcanari.net.http.InterceptedHttpsURLConnection.connect(InterceptedHttpsURLConnection.java:87)
        at com.sun.webkit.network.URLLoader.sendRequest(URLLoader.java:353)
        at com.sun.webkit.network.URLLoader.doRun(URLLoader.java:162)
        at com.sun.webkit.network.URLLoader.lambda$run$91(URLLoader.java:128)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.webkit.network.URLLoader.run(URLLoader.java:127)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

Exception in thread "JavaFX Application Thread" java.lang.NoClassDefFoundError: com/sun/javafx/Utils
        at org.controlsfx.tools.Platform.getCurrentPlatform(Platform.java:65)
        at org.controlsfx.tools.Platform.<clinit>(Platform.java:41)
        at org.controlsfx.dialog.FXDialog.init(FXDialog.java:160)
        at org.controlsfx.dialog.LightweightDialog.<init>(LightweightDialog.java:122)
        at org.controlsfx.dialog.Dialog.<init>(Dialog.java:337)
        at org.controlsfx.dialog.Dialogs.buildDialog(Dialogs.java:1023)
        at org.controlsfx.dialog.Dialogs.showSimpleContentDialog(Dialogs.java:1044)
        at org.controlsfx.dialog.Dialogs.showInformation(Dialogs.java:566)
        at com.redcanari.ui.WebKitBrowser.workerStateChanged(WebKitBrowser.java:558)
        at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:361)
        at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
        at javafx.beans.property.ReadOnlyObjectWrapper$ReadOnlyPropertyImpl.fireValueChangedEvent(ReadOnlyObjectWrapper.java:176)
        at javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:142)
        at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112)
        at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:146)
        at javafx.scene.web.WebEngine$LoadWorker.updateState(WebEngine.java:1260)
        at javafx.scene.web.WebEngine$LoadWorker.dispatchLoadEvent(WebEngine.java:1376)
        at javafx.scene.web.WebEngine$LoadWorker.access$1200(WebEngine.java:1253)
        at javafx.scene.web.WebEngine$PageLoadListener.dispatchLoadEvent(WebEngine.java:1240)
        at com.sun.webkit.WebPage.fireLoadEvent(WebPage.java:2400)
        at com.sun.webkit.WebPage.fwkFireLoadEvent(WebPage.java:2244)
        at com.sun.webkit.network.URLLoader.twkDidFail(Native Method)
        at com.sun.webkit.network.URLLoader.notifyDidFail(URLLoader.java:862)
        at com.sun.webkit.network.URLLoader.lambda$didFail$97(URLLoader.java:845)
        at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.sun.javafx.Utils
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 31 more
```

Maybe related to this (first answer): http://stackoverflow.com/questions/32440763/cant-seem-to-run-javafx-project-in-eclipse

**Comment by allfro** [comment]
It looks like you may be running another service on the same local port?

**Comment by Shaika-Dzari** [comment]
My apologies, you were right. Syncthing was running on 8080. Everything working fine.

**Comment by allfro** [comment]
Another thing to note is that BurpKit is unable to dynamically query the proxy listeners in Burp because it is not part of the Burp Extender API. So it will always assume Burp is listening on localhost:8080. I will add a settings page in the next release that will clarify this limitation.
